export const MODEL_MAP: Record<string, string[]> = {
  "opel": [
    "Astra F","Astra G","Astra H","Astra J","Astra K",
    "Corsa A","Corsa B","Corsa C","Corsa D","Corsa E","Corsa F",
    "Zafira A","Zafira B","Zafira C",
    "Combo B","Combo C","Combo D","Combo E",
    "Insignia A","Insignia B",
    "Vectra A","Vectra B","Vectra C",
    "Omega A","Omega B",
    "Meriva A","Meriva B",
    "Mokka","Mokka X",
    "Crossland X","Grandland X",
    "Kadett E","Antara","Adam","Agila B","Signum","Cascada",
  ],
  "chevrolet": [
    "Aveo T200","Aveo T250","Aveo T300",
    "Cruze J300","Cruze J400",
    "Spark M200","Spark M300",
    "Captiva C100","Captiva C140",
    "Lacetti","Epica","Trax","Orlando","Malibu",
  ],
  "bmw": [
    "1 Serisi E81","1 Serisi E87","1 Serisi F20","1 Serisi F40",
    "2 Serisi F22","2 Serisi F45","2 Serisi G42",
    "3 Serisi E30","3 Serisi E36","3 Serisi E46","3 Serisi E90","3 Serisi F30","3 Serisi G20",
    "4 Serisi F32","4 Serisi G22",
    "5 Serisi E34","5 Serisi E39","5 Serisi E60","5 Serisi F10","5 Serisi G30",
    "6 Serisi E63","6 Serisi F12",
    "7 Serisi E38","7 Serisi E65","7 Serisi F01","7 Serisi G11",
    "X1 E84","X1 F48","X1 U11",
    "X3 E83","X3 F25","X3 G01",
    "X5 E53","X5 E70","X5 F15","X5 G05",
    "X6 E71","X6 F16",
    "M3 E36","M3 E46","M3 E90","M3 F80",
    "M5 E39","M5 E60","M5 F10",
    "Z4 E85","Z4 E89",
  ],
  "mercedes-benz": [
    "A Serisi W168","A Serisi W169","A Serisi W176","A Serisi W177",
    "B Serisi W245","B Serisi W246","B Serisi W247",
    "C Serisi W202","C Serisi W203","C Serisi W204","C Serisi W205","C Serisi W206",
    "E Serisi W210","E Serisi W211","E Serisi W212","E Serisi W213",
    "S Serisi W220","S Serisi W221","S Serisi W222",
    "GLA X156","GLA X247",
    "GLC X253","GLE W166","GLE W167","GLS X166",
    "CLA C117","CLA C118","CLS C218","CLS C257",
    "Sprinter W901","Sprinter W906","Sprinter W907",
    "Vito W638","Vito W639","Vito W447",
  ],
  "volkswagen": [
    "Golf I","Golf II","Golf III","Golf IV","Golf V","Golf VI","Golf VII","Golf VIII",
    "Passat B3","Passat B4","Passat B5","Passat B6","Passat B7","Passat B8",
    "Polo 6N","Polo 6N2","Polo 9N","Polo 6R","Polo AW",
    "Tiguan I","Tiguan II",
    "Touareg I","Touareg II","Touareg III",
    "T-Roc","T-Cross","Arteon",
    "Caddy I","Caddy II","Caddy III","Caddy IV",
    "Transporter T4","Transporter T5","Transporter T6",
    "Amarok I","Amarok II","Sharan I","Sharan II",
    "ID.3","ID.4",
  ],
  "audi": [
    "A1 8X","A1 GB",
    "A3 8L","A3 8P","A3 8V","A3 8Y",
    "A4 B5","A4 B6","A4 B7","A4 B8","A4 B9",
    "A5 8T","A5 F5",
    "A6 C4","A6 C5","A6 C6","A6 C7","A6 C8",
    "A7 4G","A7 4K",
    "A8 D2","A8 D3","A8 D4","A8 D5",
    "Q2","Q3 8U","Q3 F3",
    "Q5 8R","Q5 FY",
    "Q7 4L","Q7 4M","Q8 4M",
    "TT 8N","TT 8J","TT 8S",
    "RS3","RS4 B5","RS4 B7","RS4 B8","RS6 C5","RS6 C7",
    "S3 8L","S3 8P","S4 B5","S4 B6","S4 B8",
  ],
  "ford": [
    "Focus I","Focus II","Focus III","Focus IV",
    "Fiesta III","Fiesta IV","Fiesta V","Fiesta VI","Fiesta VII",
    "Mondeo I","Mondeo II","Mondeo III","Mondeo IV","Mondeo V",
    "Kuga I","Kuga II","Kuga III",
    "EcoSport","Puma II",
    "Galaxy I","Galaxy II","Galaxy III",
    "S-MAX I","S-MAX II",
    "Transit V184","Transit V347","Transit V363",
    "Tourneo Connect","Tourneo Custom",
    "Ranger III","Ranger IV",
    "Mustang V","Mustang VI",
  ],
  "seat": [
    "Ibiza I","Ibiza II","Ibiza III","Ibiza IV","Ibiza V",
    "Leon I","Leon II","Leon III","Leon IV",
    "Toledo I","Toledo II","Toledo III","Toledo IV",
    "Ateca","Arona","Tarraco","Altea","Alhambra II",
  ],
  "skoda": [
    "Fabia I","Fabia II","Fabia III",
    "Octavia I","Octavia II","Octavia III","Octavia IV",
    "Superb I","Superb II","Superb III",
    "Yeti","Kamiq","Karoq","Kodiaq",
    "Rapid","Scala","Enyaq",
  ],
  "renault": [
    "Clio I","Clio II","Clio III","Clio IV","Clio V",
    "Megane I","Megane II","Megane III","Megane IV",
    "Laguna I","Laguna II","Laguna III",
    "Scenic I","Scenic II","Scenic III",
    "Kadjar","Captur I","Captur II",
    "Koleos I","Koleos II",
    "Sandero I","Sandero II","Sandero III",
    "Symbol I","Symbol II","Symbol III",
    "Fluence","Talisman",
    "Kangoo I","Kangoo II","Kangoo III",
    "Master II","Master III","Trafic II","Trafic III",
  ],
  "peugeot": [
    "106","107","108",
    "206","207","208 I","208 II",
    "306","307","308 I","308 II",
    "407","408","508 I","508 II",
    "2008 I","2008 II","3008 I","3008 II","5008 I","5008 II",
    "Partner I","Partner II","Partner III",
    "Expert I","Expert II","Boxer II","Boxer III",
  ],
  "citroen": [
    "C1 I","C1 II",
    "C2","C3 I","C3 II","C3 III",
    "C4 I","C4 II","C4 III",
    "C5 I","C5 II","C5 X",
    "C3 Aircross","C4 Cactus","C5 Aircross",
    "Berlingo I","Berlingo II","Berlingo III",
    "Jumpy I","Jumpy II","Jumpy III",
    "Jumper I","Jumper II",
    "C6",
  ],
  "fiat": [
    "500 312","500 334",
    "Punto I","Punto II","Punto III",
    "Doblo I","Doblo II","Doblo III",
    "Fiorino III","Fiorino IV",
    "Tipo I","Tipo II",
    "Bravo II","Stilo",
    "Linea","Egea","500X","Panda II","Panda III",
    "Uno II",
  ],
  "toyota": [
    "Corolla E10","Corolla E11","Corolla E12","Corolla E15","Corolla E16","Corolla E21",
    "Yaris P1","Yaris P2","Yaris P3","Yaris P4",
    "Auris I","Auris II",
    "Avensis I","Avensis II","Avensis III",
    "RAV4 I","RAV4 II","RAV4 III","RAV4 IV","RAV4 V",
    "Land Cruiser J100","Land Cruiser J150","Land Cruiser J200","Land Cruiser J300",
    "Hilux VII","Hilux VIII",
    "Prius II","Prius III","Prius IV",
    "C-HR","Camry VII","Camry VIII",
    "Aygo I","Aygo II",
  ],
  "hyundai": [
    "i10 I","i10 II","i10 III",
    "i20 I","i20 II","i20 III",
    "i30 I","i30 II","i30 III",
    "i40 I",
    "Accent III","Accent IV",
    "Elantra IV","Elantra V","Elantra VI",
    "Sonata IV","Sonata V",
    "Tucson I","Tucson II","Tucson III","Tucson IV",
    "Santa Fe I","Santa Fe II","Santa Fe III","Santa Fe IV",
    "ix35","Kona","Ioniq","H-1 II",
  ],
  "kia": [
    "Picanto I","Picanto II","Picanto III",
    "Rio I","Rio II","Rio III","Rio IV",
    "Ceed I","Ceed II","Ceed III",
    "Sportage I","Sportage II","Sportage III","Sportage IV","Sportage V",
    "Sorento I","Sorento II","Sorento III","Sorento IV",
    "Soul I","Soul II","Soul III",
    "Niro I","Stonic","ProCeed","EV6",
  ],
  "honda": [
    "Civic IV","Civic V","Civic VI","Civic VII","Civic VIII","Civic IX","Civic X","Civic XI",
    "Jazz I","Jazz II","Jazz III","Jazz IV",
    "CR-V I","CR-V II","CR-V III","CR-V IV","CR-V V",
    "HR-V I","HR-V II","HR-V III",
    "Accord V","Accord VI","Accord VII","Accord VIII",
    "FR-V",
  ],
  "nissan": [
    "Micra K11","Micra K12","Micra K13","Micra K14",
    "Note E11","Note E12",
    "Juke F15","Juke F16",
    "Qashqai J10","Qashqai J11","Qashqai J12",
    "X-Trail T30","X-Trail T31","X-Trail T32",
    "Navara D22","Navara D40","Navara D23",
    "Leaf ZE0","Leaf ZE1","Pulsar C13",
  ],
  "mazda": [
    "Mazda 2 DJ","Mazda 2 DY",
    "Mazda 3 BK","Mazda 3 BL","Mazda 3 BM","Mazda 3 BP",
    "Mazda 6 GG","Mazda 6 GH","Mazda 6 GJ","Mazda 6 GL",
    "CX-3","CX-5 KE","CX-5 KF","CX-9",
    "MX-5 NA","MX-5 NB","MX-5 NC","MX-5 ND",
    "626 GE","323 BJ",
  ],
  "volvo": [
    "V40 I","V40 II","V60 I","V60 II","V70 I","V70 II","V70 III","V90 I","V90 II",
    "S40 I","S40 II","S60 I","S60 II","S60 III","S80 I","S80 II","S90 II",
    "XC40","XC60 I","XC60 II","XC90 I","XC90 II",
  ],
  "mitsubishi": [
    "Colt VI","Colt VII","Galant VIII","Galant IX",
    "Outlander I","Outlander II","Outlander III","Eclipse Cross","ASX",
    "L200 III","L200 IV","L200 V","Pajero III","Pajero IV","Space Star II",
  ],
  "suzuki": [
    "Swift I","Swift II","Swift III","Swift IV","Swift V",
    "Vitara I","Vitara II","Vitara III","Baleno I","Baleno II",
    "Jimny III","Jimny IV","Ignis I","Ignis II","S-Cross I","S-Cross II",
    "Grand Vitara II","Grand Vitara III",
  ],
  "jeep": [
    "Wrangler TJ","Wrangler JK","Wrangler JL",
    "Cherokee XJ","Cherokee KJ","Cherokee KL",
    "Grand Cherokee WJ","Grand Cherokee WK","Grand Cherokee WK2","Grand Cherokee WL",
    "Renegade BU","Compass MK49","Compass MP52","Commander XK","Gladiator JT",
  ],
  "land rover": [
    "Defender 90","Defender 110","Defender L663",
    "Discovery I","Discovery II","Discovery III","Discovery IV","Discovery V",
    "Freelander I","Freelander II",
    "Range Rover I","Range Rover II","Range Rover III","Range Rover IV","Range Rover V",
    "Range Rover Sport I","Range Rover Sport II",
    "Range Rover Evoque I","Range Rover Evoque II","Velar",
  ],
  "alfa romeo": [
    "Giulia 952","Stelvio 949","Giulietta 940","MiTo 955",
    "147 937","156 932","159 939","Brera 939",
  ],
  "dacia": [
    "Sandero I","Sandero II","Sandero III",
    "Logan I","Logan II","Logan III",
    "Duster I","Duster II","Duster III","Lodgy","Dokker","Spring",
  ],
  "porsche": [
    "911 996","911 997","911 991","911 992",
    "Cayenne 9PA","Cayenne 92A","Cayenne E3",
    "Macan 95B","Panamera 970","Panamera 971",
    "Boxster 986","Boxster 987","Boxster 981","Boxster 982",
    "Cayman 987","Cayman 981","Taycan",
  ],
  "subaru": [
    "Impreza GC","Impreza GD","Impreza GE","Impreza GP","Impreza GJ","Impreza GT",
    "Legacy III","Legacy IV","Legacy V",
    "Outback II","Outback III","Outback IV","Outback V",
    "Forester I","Forester II","Forester III","Forester IV","Forester V",
    "XV I","XV II","BRZ I","BRZ II",
  ],
  "saab": ["9-3 YS3D","9-3 YS3F","9-5 YS3E","9-5 YS3G","9000"],
  "lexus": [
    "IS200","IS220","IS250","IS300h","IS350","ES300h","ES350",
    "GS300","GS430","GS450h","LS400","LS430","LS460","LS500h",
    "UX250h","NX200t","NX300h","NX350h",
    "RX300","RX330","RX350","RX450h","LX470","LX570","CT200h",
  ],
  "tofas": [
    "Doğan","Doğan SLX","Şahin","Şahin S","Kartal","Kartal SLX",
    "Tempra","Fiorino","Brava","Uno",
  ],
};

export function getVehicleModels(brandLabel: string): string[] {
  const key = brandLabel.toLowerCase();
  return MODEL_MAP[key] ?? [];
}
